// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Park struct {
	ID          uuid.UUID
	NpsID       string
	FullName    string
	ParkCode    string
	States      string
	Description string
	Designation string
	Activities  json.RawMessage
	Topics      json.RawMessage
	Details     json.RawMessage
	CreatedAt   time.Time
}
