// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parks.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO parks (id, nps_id, full_name, park_code, states, description, designation, activities, topics, details, created_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
RETURNING id, nps_id, full_name, park_code, states, description, designation, activities, topics, details, created_at
`

type CreateUserParams struct {
	ID          uuid.UUID
	NpsID       string
	FullName    string
	ParkCode    string
	States      string
	Description string
	Designation string
	Activities  json.RawMessage
	Topics      json.RawMessage
	Details     json.RawMessage
	CreatedAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Park, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.NpsID,
		arg.FullName,
		arg.ParkCode,
		arg.States,
		arg.Description,
		arg.Designation,
		arg.Activities,
		arg.Topics,
		arg.Details,
		arg.CreatedAt,
	)
	var i Park
	err := row.Scan(
		&i.ID,
		&i.NpsID,
		&i.FullName,
		&i.ParkCode,
		&i.States,
		&i.Description,
		&i.Designation,
		&i.Activities,
		&i.Topics,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}
